// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Description = "A young German Shepherd who loves playing frisbee.",
                            Name = "Emily",
                            Sex = "Female",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Description = "A sweet, mixed breed dog that is always happy to sit on a lap.",
                            Name = "Benjie",
                            Sex = "Male",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            Description = "A playful black cat without a care in the world.",
                            Name = "Sasha",
                            Sex = "Female",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Description = "An excitable tabby who loves to lay in the sun.",
                            Name = "O'Bryan",
                            Sex = "Male",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 7,
                            Description = "A confident hairless cat that knows every last detail of her environment.",
                            Name = "Gertrude",
                            Sex = "Female",
                            Type = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
